package problem

import (
	"encoding/json"
	"fmt"
	"net/http"
)

const (
	// ContentTypeJSON https://tools.ietf.org/html/rfc7807#section-6.1
	ContentTypeJSON = "application/problem+json"
)

func New() problemBuilder {
	return problemBuilder{
		Problem: &Problem{
			data: map[string]any{},
		},
	}
}

// Problem details object can have the following members:
//
//   - "type" (string) - A URI reference [RFC3986] that identifies the
//     Problem type.  This specification encourages that, when
//     dereferenced, it provide human-readable documentation for the
//     Problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
//     this member is not present, its value is assumed to be
//     "about:blank".
//
//   - "title" (string) - A short, human-readable summary of the Problem
//     type.  It SHOULD NOT change from occurrence to occurrence of the
//     Problem, except for purposes of localization (e.g., using
//     proactive content negotiation; see [RFC7231], Section 3.4).
//
//   - "status" (number) - The HTTP status code ([RFC7231], Section 6)
//     generated by the origin server for this occurrence of the Problem.
//
//   - "detail" (string) - A human-readable explanation specific to this
//     occurrence of the Problem.
//
//   - "instance" (string) - A URI reference that identifies the specific
//     occurrence of the Problem.  It may or may not yield further
//     information if dereferenced.
type Problem struct {
	cause error
	data  map[string]any
}

func (p *Problem) Error() string {
	if p.cause != nil {
		return p.cause.Error()
	}
	return fmt.Sprintf("[status=%v reason=%v title=%v type=%v]", p.data["status"], p.data["reason"], p.data["title"], p.data["type"])
}

// UnmarshalJSON implements the json.Unmarshaler interface
func (p *Problem) UnmarshalJSON(b []byte) error {
	return json.Unmarshal(b, &p.data)
}

// MarshalJSON implements the json.Marshaler interface
func (p Problem) MarshalJSON() ([]byte, error) {
	return json.Marshal(&p.data)
}

// Is compares Problem.Error() with err.Error()
func (p Problem) Is(err error) bool {
	return p.Error() == err.Error()
}

// Unwrap returns the result of calling the Unwrap method on err, if err implements Unwrap.
// Otherwise, Unwrap returns nil.
func (p Problem) Unwrap() error {
	return p.cause
}

// WriteHeaderTo writes the HTTP headers for the JSON Problem ContentType and the
// problem's HTTP statuscode. This is suitable for responding to HEAD requests.
func (p Problem) WriteHeaderTo(w http.ResponseWriter) {
	w.Header().Set("Content-Type", ContentTypeJSON)
	status := 500
	if statuscode, ok := p.data["status"]; ok {
		if statusint, ok := statuscode.(int); ok {
			status = statusint
		}

	}
	w.WriteHeader(status)
}

// WriteTo writes the JSON Problem to an HTTP Response Writer using the correct
// Content-Type and the problem's HTTP statuscode
func (p Problem) WriteTo(w http.ResponseWriter) error {
	p.WriteHeaderTo(w)
	return json.NewEncoder(w).Encode(p)
}

type problemBuilder struct {
	*Problem
}

func (b problemBuilder) Of(code int) *Problem {
	return b.
		Status(code).
		Title(http.StatusText(code)).
		Problem
}

func (b problemBuilder) Status(code int) problemBuilder {
	b.data["status"] = code
	return b
}

// Title sets a title that appropriately describes it (think short)
// Written in english and readable for engineers (usually not suited for
// non technical stakeholders and not localized); example: Service Unavailable
func (b problemBuilder) Title(title string) problemBuilder {
	b.data["title"] = title
	return b
}

// Wrap an error to the Problem
func (b problemBuilder) Wrap(err error) problemBuilder {
	b.Problem.cause = err
	b.Problem.data["reason"] = err.Error()
	return b
}

// WrapSilent wraps an error without making that error public (ie. visible in the response).
func (b problemBuilder) WrapSilent(err error) problemBuilder {
	b.Problem.cause = err
	return b
}

// Detail A human readable explanation specific to this occurrence of the problem.
func (b problemBuilder) Detail(detail string) problemBuilder {
	b.Problem.data["detail"] = detail
	return b
}

func (b problemBuilder) WriteTo(w http.ResponseWriter) error {
	return b.Problem.WriteTo(w)
}

func (b problemBuilder) Build() *Problem {
	return b.Problem
}
